spring.application.name=myApigateway
server.port=3333
spring.boot.admin.client.url=http://localhost:1111
management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=read-only
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.reactor.netty.http.client=DEBUG
spring.config.import=optional:configserver:http://localhost:4444

#greet service
spring.cloud.gateway.server.webflux.routes[0].id=route1
spring.cloud.gateway.server.webflux.routes[0].uri=lb://GREETAPI
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/greet/**
#spring.cloud.gateway.routes[0].predicates[0]=Path=/greet/hello
#welcome service
spring.cloud.gateway.server.webflux.routes[1].id=route2
spring.cloud.gateway.server.webflux.routes[1].uri=lb://WELCOMAPI
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/message
